### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by lodenrogue** [jian01/GiaNLP#9]
I came across your repo when searching for issues tagged with `good-first-issue` but I wasn't able to understand what the project was about or how to help with the issue.

Please consider adding a README with an explanation of what the project is about and how to build and run it.

**Comment by jian01** [comment]
Hi Miguel, thank you for your interest. This is a library developed at Mercadolibre and soon to become open source. The library has the goal to be a bridge between NLP preprocessing needed for keras, and custom keras models, allowing the building of complex and huge models with multiple ways of representing text without having to deal with the preprocessing. The library wraps your keras architecture and let's you train directly with texts as x values, respecting all the keras API (you can use generators, sequences, multiprocessing, use the model as the input of a vainilla keras model, etc). This is already in production at some limited projects in Mercadolibre.

My roadmap is:

- Finish little refactors
- Create all the testing and linting pipelines
- Migrate the documentation and examples from Mercadolibre to a more friendly format, along with writing the readme
- Release the first version to pypi (merge initial_setup to main)
- Then start to iterate over the features

I plan to have the first version release ready for next weekend :) so the wait wont be long

**Comment by jian01** [comment]
I will add something similar to this I just wrote to you to the readme. Also I need to be more descriptive at the issues, I will try to add some detail after the first release to each of one!
